"""
Comprehensive sports team database with real-world inspired stats.
Covers Soccer, Basketball, and American Football.
"""

from typing import Dict, List, Any

SPORTS = [
    {"id": "soccer", "name": "Soccer", "icon": "goal"},
    {"id": "basketball", "name": "Basketball", "icon": "basketball"},
    {"id": "american_football", "name": "American Football", "icon": "football"},
]

TEAMS: Dict[str, Dict[str, Any]] = {
    # ========== SOCCER TEAMS ==========
    "soccer_mancity": {
        "id": "soccer_mancity",
        "name": "Manchester City",
        "sport": "soccer",
        "league": "Premier League",
        "country": "England",
        "logo_color": "#6CABDD",
        "formation": "4-3-3",
        "style": "Possession-based",
        "stats": {
            "attack": 94,
            "defense": 87,
            "midfield": 95,
            "set_pieces": 80,
            "pace": 85,
            "physicality": 82,
            "pressing": 93,
            "possession": 96,
            "crossing": 78,
            "finishing": 91,
        },
        "key_players": ["Erling Haaland", "Kevin De Bruyne", "Rodri", "Bernardo Silva"],
        "tactical_notes": "Elite possession game with high pressing. Inverted fullbacks create numerical superiority in midfield. Haaland provides lethal finishing as the focal point of attacks.",
        "strengths": ["Ball retention", "High press", "Creative midfield", "Clinical finishing", "Squad depth"],
        "weaknesses": ["Vulnerability on counter-attacks", "Set-piece defending", "Aging key players"],
        "recent_form": ["W", "W", "D", "W", "W"],
        "season_record": {"wins": 25, "draws": 5, "losses": 3, "goals_for": 78, "goals_against": 28},
    },
    "soccer_realmadrid": {
        "id": "soccer_realmadrid",
        "name": "Real Madrid",
        "sport": "soccer",
        "league": "La Liga",
        "country": "Spain",
        "logo_color": "#FEBE10",
        "formation": "4-3-1-2",
        "style": "Counter-attacking / Adaptive",
        "stats": {
            "attack": 93,
            "defense": 85,
            "midfield": 90,
            "set_pieces": 83,
            "pace": 92,
            "physicality": 84,
            "pressing": 80,
            "possession": 85,
            "crossing": 88,
            "finishing": 92,
        },
        "key_players": ["Vinicius Jr", "Jude Bellingham", "Kylian Mbappe", "Toni Kroos"],
        "tactical_notes": "Devastating on the counter with extreme pace on the flanks. Bellingham provides goals from midfield. Adaptable system that shifts between possession and direct play.",
        "strengths": ["Counter-attack speed", "Big-game mentality", "Individual brilliance", "Aerial presence"],
        "weaknesses": ["Inconsistent pressing", "Defensive transitions", "Over-reliance on key individuals"],
        "recent_form": ["W", "W", "W", "D", "W"],
        "season_record": {"wins": 24, "draws": 6, "losses": 3, "goals_for": 75, "goals_against": 30},
    },
    "soccer_bayern": {
        "id": "soccer_bayern",
        "name": "Bayern Munich",
        "sport": "soccer",
        "league": "Bundesliga",
        "country": "Germany",
        "logo_color": "#DC052D",
        "formation": "4-2-3-1",
        "style": "High-pressing / Possession",
        "stats": {
            "attack": 91,
            "defense": 88,
            "midfield": 89,
            "set_pieces": 82,
            "pace": 88,
            "physicality": 86,
            "pressing": 94,
            "possession": 90,
            "crossing": 85,
            "finishing": 88,
        },
        "key_players": ["Harry Kane", "Jamal Musiala", "Joshua Kimmich", "Leroy Sane"],
        "tactical_notes": "Aggressive high-line pressing system with Kane as the complete striker. Musiala provides creative spark while Kimmich dictates tempo from deep. Wide overloads create space.",
        "strengths": ["Relentless pressing", "Kane's movement", "Midfield control", "Wide play"],
        "weaknesses": ["High defensive line exploitable", "Occasional complacency", "Squad rotation concerns"],
        "recent_form": ["W", "D", "W", "W", "L"],
        "season_record": {"wins": 22, "draws": 5, "losses": 6, "goals_for": 80, "goals_against": 35},
    },
    "soccer_liverpool": {
        "id": "soccer_liverpool",
        "name": "Liverpool",
        "sport": "soccer",
        "league": "Premier League",
        "country": "England",
        "logo_color": "#C8102E",
        "formation": "4-3-3",
        "style": "Gegenpressing / High Intensity",
        "stats": {
            "attack": 90,
            "defense": 86,
            "midfield": 88,
            "set_pieces": 79,
            "pace": 91,
            "physicality": 87,
            "pressing": 95,
            "possession": 82,
            "crossing": 86,
            "finishing": 87,
        },
        "key_players": ["Mohamed Salah", "Virgil van Dijk", "Trent Alexander-Arnold", "Darwin Nunez"],
        "tactical_notes": "Intense gegenpressing system that wins the ball high up the pitch. Salah cuts inside from the right, Alexander-Arnold provides creative passing from fullback. Extremely high-energy system.",
        "strengths": ["Gegenpressing intensity", "Fast transitions", "Salah's consistency", "Set-piece threat from TAA"],
        "weaknesses": ["Energy management over season", "Defensive vulnerabilities in transition", "Inconsistent finishing"],
        "recent_form": ["W", "L", "W", "W", "D"],
        "season_record": {"wins": 21, "draws": 7, "losses": 5, "goals_for": 70, "goals_against": 32},
    },
    "soccer_barcelona": {
        "id": "soccer_barcelona",
        "name": "FC Barcelona",
        "sport": "soccer",
        "league": "La Liga",
        "country": "Spain",
        "logo_color": "#A50044",
        "formation": "4-3-3",
        "style": "Tiki-taka / Positional Play",
        "stats": {
            "attack": 89,
            "defense": 82,
            "midfield": 92,
            "set_pieces": 77,
            "pace": 86,
            "physicality": 78,
            "pressing": 87,
            "possession": 94,
            "crossing": 80,
            "finishing": 86,
        },
        "key_players": ["Lamine Yamal", "Robert Lewandowski", "Pedri", "Gavi"],
        "tactical_notes": "Classic Barcelona positional play with emphasis on short passing and movement. Young talents like Yamal provide pace and directness. Pedri orchestrates from midfield with exceptional vision.",
        "strengths": ["Youth development", "Positional play", "Technical quality", "Midfield dominance"],
        "weaknesses": ["Defensive fragility", "Physical battles", "European knockout inconsistency"],
        "recent_form": ["W", "W", "D", "L", "W"],
        "season_record": {"wins": 22, "draws": 4, "losses": 7, "goals_for": 68, "goals_against": 34},
    },
    "soccer_arsenal": {
        "id": "soccer_arsenal",
        "name": "Arsenal",
        "sport": "soccer",
        "league": "Premier League",
        "country": "England",
        "logo_color": "#EF0107",
        "formation": "4-3-3",
        "style": "Progressive Build-up / Set-piece Mastery",
        "stats": {
            "attack": 88,
            "defense": 89,
            "midfield": 87,
            "set_pieces": 93,
            "pace": 84,
            "physicality": 85,
            "pressing": 88,
            "possession": 86,
            "crossing": 82,
            "finishing": 85,
        },
        "key_players": ["Bukayo Saka", "Martin Odegaard", "William Saliba", "Declan Rice"],
        "tactical_notes": "Arteta's system combines progressive build-up play with deadly set-piece routines. Saka is the primary creative threat. Rice provides box-to-box dynamism while Saliba anchors the defense.",
        "strengths": ["Set-piece dominance", "Defensive solidity", "Squad unity", "Tactical flexibility"],
        "weaknesses": ["Lack of elite striker", "Over-reliance on Saka", "Title-race experience"],
        "recent_form": ["W", "W", "W", "D", "W"],
        "season_record": {"wins": 23, "draws": 6, "losses": 4, "goals_for": 72, "goals_against": 26},
    },

    # ========== BASKETBALL TEAMS ==========
    "basketball_celtics": {
        "id": "basketball_celtics",
        "name": "Boston Celtics",
        "sport": "basketball",
        "league": "NBA",
        "country": "USA",
        "logo_color": "#007A33",
        "formation": "5-out Motion",
        "style": "Switch-everything Defense / 3PT Heavy",
        "stats": {
            "offense": 95,
            "defense": 93,
            "three_point": 96,
            "rebounding": 85,
            "playmaking": 88,
            "athleticism": 87,
            "clutch": 90,
            "depth": 88,
            "fast_break": 82,
            "post_play": 75,
        },
        "key_players": ["Jayson Tatum", "Jaylen Brown", "Derrick White", "Kristaps Porzingis"],
        "tactical_notes": "Elite 3-point shooting team with switch-everything defensive scheme. Tatum and Brown provide two-way star power. Porzingis stretches the floor as a 7-footer with range.",
        "strengths": ["3-point volume and efficiency", "Defensive versatility", "Two-way wings", "Coaching system"],
        "weaknesses": ["Sometimes over-reliant on 3s", "Half-court offense can stagnate", "Rim protection without Porzingis"],
        "recent_form": ["W", "W", "W", "L", "W"],
        "season_record": {"wins": 55, "losses": 15, "points_per_game": 118.5, "points_allowed": 108.2},
    },
    "basketball_nuggets": {
        "id": "basketball_nuggets",
        "name": "Denver Nuggets",
        "sport": "basketball",
        "league": "NBA",
        "country": "USA",
        "logo_color": "#0E2240",
        "formation": "Jokic-centric Offense",
        "style": "Point-center Orchestration / Pick & Roll",
        "stats": {
            "offense": 94,
            "defense": 86,
            "three_point": 83,
            "rebounding": 90,
            "playmaking": 95,
            "athleticism": 82,
            "clutch": 92,
            "depth": 80,
            "fast_break": 78,
            "post_play": 96,
        },
        "key_players": ["Nikola Jokic", "Jamal Murray", "Michael Porter Jr", "Aaron Gordon"],
        "tactical_notes": "Entire offense flows through Jokic as the greatest passing big man ever. Murray provides clutch scoring in playoffs. MPJ's size and shooting stretches defenses. Gordon is the defensive anchor.",
        "strengths": ["Jokic's passing and scoring", "Playoff experience", "Half-court execution", "Rebounding dominance"],
        "weaknesses": ["Perimeter defense", "Depth concerns", "Reliance on Jokic health", "Transition defense"],
        "recent_form": ["W", "W", "D", "W", "L"],
        "season_record": {"wins": 50, "losses": 20, "points_per_game": 115.8, "points_allowed": 110.5},
    },
    "basketball_thunder": {
        "id": "basketball_thunder",
        "name": "OKC Thunder",
        "sport": "basketball",
        "league": "NBA",
        "country": "USA",
        "logo_color": "#007AC1",
        "formation": "Motion Offense / Switching D",
        "style": "Athletic / High-pace / Disruptive Defense",
        "stats": {
            "offense": 90,
            "defense": 92,
            "three_point": 85,
            "rebounding": 88,
            "playmaking": 89,
            "athleticism": 95,
            "clutch": 88,
            "depth": 91,
            "fast_break": 93,
            "post_play": 78,
        },
        "key_players": ["Shai Gilgeous-Alexander", "Chet Holmgren", "Jalen Williams", "Lu Dort"],
        "tactical_notes": "Youngest elite team in the NBA with incredible athleticism. SGA is an elite shot-creator. Holmgren provides rim protection and floor spacing. Defense generates turnovers that fuel fast breaks.",
        "strengths": ["Youth and athleticism", "Defensive disruption", "Fast break scoring", "Squad depth"],
        "weaknesses": ["Playoff experience", "Half-court offense in crunch time", "Physical matchups vs bigger teams"],
        "recent_form": ["W", "W", "W", "W", "L"],
        "season_record": {"wins": 52, "losses": 18, "points_per_game": 116.2, "points_allowed": 107.8},
    },
    "basketball_lakers": {
        "id": "basketball_lakers",
        "name": "Los Angeles Lakers",
        "sport": "basketball",
        "league": "NBA",
        "country": "USA",
        "logo_color": "#552583",
        "formation": "LeBron-centric / Pick & Roll",
        "style": "Star-driven / Versatile",
        "stats": {
            "offense": 88,
            "defense": 84,
            "three_point": 80,
            "rebounding": 87,
            "playmaking": 91,
            "athleticism": 83,
            "clutch": 89,
            "depth": 76,
            "fast_break": 85,
            "post_play": 88,
        },
        "key_players": ["LeBron James", "Anthony Davis", "Austin Reaves", "D'Angelo Russell"],
        "tactical_notes": "LeBron orchestrates the offense with elite court vision while AD dominates the paint. Reaves has emerged as a reliable third option. Team relies heavily on its stars performing.",
        "strengths": ["LeBron's IQ and passing", "AD's two-way dominance", "Big-game experience", "Paint scoring"],
        "weaknesses": ["Roster depth", "3-point shooting inconsistency", "Age of core players", "Perimeter defense"],
        "recent_form": ["W", "L", "W", "L", "W"],
        "season_record": {"wins": 42, "losses": 28, "points_per_game": 113.5, "points_allowed": 112.1},
    },
    "basketball_bucks": {
        "id": "basketball_bucks",
        "name": "Milwaukee Bucks",
        "sport": "basketball",
        "league": "NBA",
        "country": "USA",
        "logo_color": "#00471B",
        "formation": "Giannis Drive & Kick",
        "style": "Paint Dominance / Drop Coverage",
        "stats": {
            "offense": 91,
            "defense": 88,
            "three_point": 84,
            "rebounding": 89,
            "playmaking": 86,
            "athleticism": 92,
            "clutch": 85,
            "depth": 82,
            "fast_break": 88,
            "post_play": 93,
        },
        "key_players": ["Giannis Antetokounmpo", "Damian Lillard", "Khris Middleton", "Brook Lopez"],
        "tactical_notes": "Giannis's drives to the rim create open shots for shooters. Lillard provides elite shot-creation and range. Lopez anchors the drop coverage defense. Paint dominance is their identity.",
        "strengths": ["Giannis's dominance", "Paint scoring", "Rim protection", "Transition offense"],
        "weaknesses": ["Perimeter defense vs elite shooters", "Halfcourt offense variety", "Health concerns"],
        "recent_form": ["W", "L", "W", "W", "W"],
        "season_record": {"wins": 48, "losses": 22, "points_per_game": 116.8, "points_allowed": 111.3},
    },

    # ========== AMERICAN FOOTBALL TEAMS ==========
    "nfl_chiefs": {
        "id": "nfl_chiefs",
        "name": "Kansas City Chiefs",
        "sport": "american_football",
        "league": "NFL",
        "country": "USA",
        "logo_color": "#E31837",
        "formation": "11 Personnel / Shotgun Spread",
        "style": "West Coast / RPO Heavy",
        "stats": {
            "passing_offense": 95,
            "rushing_offense": 78,
            "pass_defense": 85,
            "rush_defense": 83,
            "special_teams": 88,
            "coaching": 97,
            "clutch": 98,
            "red_zone": 90,
            "turnover_margin": 87,
            "discipline": 92,
        },
        "key_players": ["Patrick Mahomes", "Travis Kelce", "Chris Jones", "Rashee Rice"],
        "tactical_notes": "Mahomes's improvisational genius combined with Reid's scheming makes this offense nearly impossible to stop. Kelce remains the most reliable tight end in football. Jones disrupts from the interior.",
        "strengths": ["Mahomes's arm talent and improvisation", "Coaching and game planning", "Clutch performance", "Defensive versatility"],
        "weaknesses": ["Wide receiver depth", "Offensive line consistency", "Running game can be one-dimensional"],
        "recent_form": ["W", "W", "L", "W", "W"],
        "season_record": {"wins": 13, "losses": 4, "points_for": 420, "points_against": 298},
    },
    "nfl_49ers": {
        "id": "nfl_49ers",
        "name": "San Francisco 49ers",
        "sport": "american_football",
        "league": "NFL",
        "country": "USA",
        "logo_color": "#AA0000",
        "formation": "21 Personnel / Pistol",
        "style": "Shanahan Zone-Run / Play-Action",
        "stats": {
            "passing_offense": 86,
            "rushing_offense": 93,
            "pass_defense": 88,
            "rush_defense": 90,
            "special_teams": 82,
            "coaching": 92,
            "clutch": 80,
            "red_zone": 88,
            "turnover_margin": 84,
            "discipline": 86,
        },
        "key_players": ["Brock Purdy", "Christian McCaffrey", "Nick Bosa", "Deebo Samuel"],
        "tactical_notes": "Shanahan's zone-run scheme creates play-action opportunities that freeze defenses. McCaffrey is the ultimate chess piece. Bosa anchors an elite defensive line. Multiple weapons make this offense unpredictable.",
        "strengths": ["Zone-run scheme", "Defensive line dominance", "Offensive versatility", "Coaching innovation"],
        "weaknesses": ["Quarterback ceiling questions", "Injury concerns", "Closing out big games"],
        "recent_form": ["W", "W", "W", "L", "W"],
        "season_record": {"wins": 12, "losses": 5, "points_for": 395, "points_against": 275},
    },
    "nfl_ravens": {
        "id": "nfl_ravens",
        "name": "Baltimore Ravens",
        "sport": "american_football",
        "league": "NFL",
        "country": "USA",
        "logo_color": "#241773",
        "formation": "12/13 Personnel / Pistol",
        "style": "Run-Heavy / RPO / Dual-Threat QB",
        "stats": {
            "passing_offense": 84,
            "rushing_offense": 97,
            "pass_defense": 82,
            "rush_defense": 86,
            "special_teams": 90,
            "coaching": 88,
            "clutch": 83,
            "red_zone": 92,
            "turnover_margin": 85,
            "discipline": 84,
        },
        "key_players": ["Lamar Jackson", "Derrick Henry", "Mark Andrews", "Roquan Smith"],
        "tactical_notes": "The most devastating rushing attack in football with Jackson and Henry. RPO game is nearly impossible to defend when the run game is rolling. Smith leads an aggressive defense.",
        "strengths": ["Elite rushing attack", "Lamar's dual-threat ability", "Red zone efficiency", "Physical identity"],
        "weaknesses": ["Passing in adverse conditions", "Playoff consistency", "Pass defense vs elite QBs"],
        "recent_form": ["W", "W", "W", "W", "L"],
        "season_record": {"wins": 13, "losses": 4, "points_for": 410, "points_against": 285},
    },
    "nfl_eagles": {
        "id": "nfl_eagles",
        "name": "Philadelphia Eagles",
        "sport": "american_football",
        "league": "NFL",
        "country": "USA",
        "logo_color": "#004C54",
        "formation": "12 Personnel / RPO Heavy",
        "style": "Power Run / RPO / Aggressive Defense",
        "stats": {
            "passing_offense": 85,
            "rushing_offense": 91,
            "pass_defense": 86,
            "rush_defense": 84,
            "special_teams": 80,
            "coaching": 85,
            "clutch": 82,
            "red_zone": 87,
            "turnover_margin": 88,
            "discipline": 80,
        },
        "key_players": ["Jalen Hurts", "Saquon Barkley", "AJ Brown", "Jalen Carter"],
        "tactical_notes": "Physical, run-first identity with Hurts and Barkley forming a lethal rushing duo. Brown provides deep-threat ability. Carter leads an aggressive defensive front. RPOs are their bread and butter.",
        "strengths": ["Rushing attack", "Offensive line dominance", "Defensive line talent", "RPO execution"],
        "weaknesses": ["Second-half adjustments", "Passing consistency", "Defensive secondary depth"],
        "recent_form": ["W", "L", "W", "W", "W"],
        "season_record": {"wins": 11, "losses": 6, "points_for": 380, "points_against": 300},
    },
    "nfl_bills": {
        "id": "nfl_bills",
        "name": "Buffalo Bills",
        "sport": "american_football",
        "league": "NFL",
        "country": "USA",
        "logo_color": "#00338D",
        "formation": "11 Personnel / Spread",
        "style": "Josh Allen Hero Ball / Aggressive Defense",
        "stats": {
            "passing_offense": 92,
            "rushing_offense": 85,
            "pass_defense": 84,
            "rush_defense": 80,
            "special_teams": 83,
            "coaching": 88,
            "clutch": 86,
            "red_zone": 85,
            "turnover_margin": 82,
            "discipline": 78,
        },
        "key_players": ["Josh Allen", "Stefon Diggs", "Von Miller", "Matt Milano"],
        "tactical_notes": "Josh Allen's arm strength and rushing ability make him the most dangerous dual-threat QB. Diggs provides elite route running. Defense applies pressure with Miller leading the pass rush.",
        "strengths": ["Josh Allen's playmaking", "Deep passing game", "Pass rush", "Cold weather advantage"],
        "weaknesses": ["Turnover-prone plays", "Run defense consistency", "AFC playoff hurdle"],
        "recent_form": ["W", "W", "L", "W", "W"],
        "season_record": {"wins": 11, "losses": 6, "points_for": 385, "points_against": 310},
    },
}


def get_teams_by_sport(sport: str) -> List[Dict[str, Any]]:
    """Get all teams for a specific sport."""
    return [
        {
            "id": t["id"],
            "name": t["name"],
            "sport": t["sport"],
            "league": t["league"],
            "country": t["country"],
            "logo_color": t["logo_color"],
            "formation": t["formation"],
            "style": t["style"],
            "recent_form": t["recent_form"],
        }
        for t in TEAMS.values()
        if t["sport"] == sport
    ]


def get_team(team_id: str) -> Dict[str, Any] | None:
    """Get full team details."""
    return TEAMS.get(team_id)


def get_all_teams() -> List[Dict[str, Any]]:
    """Get summary of all teams."""
    return [
        {
            "id": t["id"],
            "name": t["name"],
            "sport": t["sport"],
            "league": t["league"],
            "country": t["country"],
            "logo_color": t["logo_color"],
            "formation": t["formation"],
            "style": t["style"],
            "recent_form": t["recent_form"],
        }
        for t in TEAMS.values()
    ]
